### ISSUE TITLE
Typos / Miscellaneous Erata in Kindle Version

### ISSUE THREAD

**Issue by andrewzey** [azat-co/practicalnode#9]
- Chapter 1 (location 873 of 8083) link to "http://callbackhell.com/):" broken
- Chapter 2 (location 1564 of 8083) reference to process.evn.PORT instead of process.env.PORT
- Chapter 2 (location 1652 of 8083) Missing opening h1 tag: 

``` html
"Produces the following HTML code: hello </h1><p>Welcome to the Practical Node.js!</p>" 
```
- Chapter 4 (location 2412 of 8083) 
  Quote: "hence the name of the library (see the resemblance to handlebars on a bicycle?". 
  Handlebars is named as such because it is a nickname for an impressive mustache. It has nothing to do with handlebars on a bicycle.
- Chapter 8 (location 5014 of 8083): refers to "Anglers JS" instead of "Angular JS".
- Chapter 8 (location 5465 of 8083): section title says "Hapi RESP API..." instead of "Hapi REST API..."
- Chapter 9 (Location 5779): example of of "full source code" of browser websocket implementation is missing error handler (ws.onerror = function(event){...} ).

**Comment by BraveKenny** [comment]
Here are some more:

* Introduction (location 333 of 8087) "there are *there* categories of programmers"

* Chapter 2 (location 1283 of 8087) "So far we've covered *Expres.js* installation."

* Chapter 2 (location 1369 of 8087) Is it just me or is the middleware code example more confusing than helping?
```
if (req.query.id) {
// process the id, then call next() when done
else if (req.query.author) {
// same approach as with id
else if (req.query.id && req.query.ref) {
// process when id and ref present
} else {
next();
}
```
Braces are opened but not closed, and the second `else if` never resolves to true since we already checked for `req.query.id` in the first `if`.

**Comment by azat-co** [comment]
fixed except the bicycle.
